## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('hirai',
                                 ['wifi', 'internet', 'hirai', 'internet-apps'])
    obj.source = 'hirai.cc'
