## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('lowbattery', ['internet', 'wifi'])
    module.includes = '.'
    module.source = [
        'model/lowbattery-packet.cc',
        'model/lowbattery-routing-protocol.cc',
        'helper/lowbattery-helper.cc',
        ]

    #lowbattery_test = bld.create_ns3_module_test_library('lowbattery')
   # lowbattery_test.source = [
      #  'test/lowbattery-id-cache-test-suite.cc',
       # 'test/lowbattery-test-suite.cc',
       # 'test/lowbattery-regression.cc',
       # 'test/bug-772.cc',
       # 'test/loopback.cc',
       # ]

    headers = bld(features='ns3header')
    headers.module = 'lowbattery'
    headers.source = [
        'model/lowbattery-packet.h',
        'model/lowbattery-routing-protocol.h',
        'helper/lowbattery-helper.h',
        ]

    #if bld.env['ENABLE_EXAMPLES']:
     #   bld.recurse('examples')

   # bld.ns3_python_bindings()
