## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('livelytower', ['internet', 'wifi'])
    module.includes = '.'
    module.source = [
        'model/livelytower-packet.cc',
        'model/livelytower-routing-protocol.cc',
        'helper/livelytower-helper.cc',
        ]

    #livelytower_test = bld.create_ns3_module_test_library('livelytower')
   # livelytower_test.source = [
      #  'test/livelytower-id-cache-test-suite.cc',
       # 'test/livelytower-test-suite.cc',
       # 'test/livelytower-regression.cc',
       # 'test/bug-772.cc',
       # 'test/loopback.cc',
       # ]

    headers = bld(features='ns3header')
    headers.module = 'livelytower'
    headers.source = [
        'model/livelytower-packet.h',
        'model/livelytower-routing-protocol.h',
        'helper/livelytower-helper.h',
        ]

    #if bld.env['ENABLE_EXAMPLES']:
     #   bld.recurse('examples')

   # bld.ns3_python_bindings()
